# Generated by Django 4.2 on 2026-03-07 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "sport",
                    models.CharField(
                        choices=[
                            ("cricket", "Cricket"),
                            ("football", "Football"),
                            ("basketball", "Basketball"),
                            ("volleyball", "Volleyball"),
                            ("badminton", "Badminton"),
                            ("table_tennis", "Table Tennis"),
                            ("athletics", "Athletics"),
                            ("swimming", "Swimming"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("coach_name", models.CharField(max_length=100)),
                ("coach_email", models.EmailField(max_length=254)),
                ("coach_phone", models.CharField(max_length=10)),
                ("team_logo", models.ImageField(upload_to="team_logos/")),
                ("members_count", models.IntegerField(default=0)),
                ("establishment_year", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Teams",
                "ordering": ["sport", "name"],
            },
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll_number", models.CharField(max_length=20, unique=True)),
                ("branch", models.CharField(max_length=50)),
                (
                    "year",
                    models.IntegerField(
                        choices=[
                            (1, "1st Year"),
                            (2, "2nd Year"),
                            (3, "3rd Year"),
                            (4, "4th Year"),
                        ]
                    ),
                ),
                ("phone", models.CharField(max_length=10)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="student_profiles/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Student Profiles",
            },
        ),
        migrations.CreateModel(
            name="StudentInterestForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll_number", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=10)),
                ("branch", models.CharField(max_length=50)),
                ("year", models.IntegerField()),
                ("past_achievements", models.TextField(blank=True)),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("professional", "Professional"),
                        ],
                        max_length=20,
                    ),
                ),
                ("additional_comments", models.TextField(blank=True)),
                ("submission_date", models.DateTimeField(auto_now_add=True)),
                ("is_reviewed", models.BooleanField(default=False)),
                ("sports_interests", models.ManyToManyField(to="sports_app.team")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interest_forms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Student Interest Forms",
                "ordering": ["-submission_date"],
            },
        ),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("event_type", models.CharField(max_length=100)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("location", models.CharField(max_length=200)),
                ("registration_deadline", models.DateTimeField()),
                ("max_participants", models.IntegerField(blank=True, null=True)),
                ("eligibility_criteria", models.TextField()),
                ("poster_image", models.ImageField(upload_to="opportunity_posters/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open for Registration"),
                            ("closed", "Closed"),
                            ("completed", "Completed"),
                            ("postponed", "Postponed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("contact_person", models.CharField(max_length=100)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to="sports_app.team",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Opportunities",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "achievement_type",
                    models.CharField(
                        choices=[
                            ("championship", "Championship"),
                            ("medal", "Medal"),
                            ("award", "Award"),
                            ("record", "Record"),
                            ("recognition", "Recognition"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("location", models.CharField(max_length=100)),
                (
                    "player_names",
                    models.TextField(
                        help_text="Enter player names separated by commas"
                    ),
                ),
                ("image", models.ImageField(upload_to="achievements/")),
                (
                    "certificate_image",
                    models.ImageField(blank=True, null=True, upload_to="certificates/"),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="sports_app.team",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Achievements",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(blank=True, max_length=100)),
                (
                    "team_members",
                    models.TextField(
                        blank=True,
                        help_text="Enter team member names separated by commas",
                    ),
                ),
                ("contact_number", models.CharField(max_length=10)),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("confirmed", "Confirmed"),
                            ("participated", "Participated"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="registered",
                        max_length=20,
                    ),
                ),
                ("confirmation_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="sports_app.opportunity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Event Registrations",
                "ordering": ["-registration_date"],
                "unique_together": {("user", "opportunity")},
            },
        ),
    ]
