# Generated by Django 4.2 on 2026-03-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sports_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High — Show as Banner"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="achievement",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterModelOptions(
            name="eventregistration",
            options={"ordering": ["-registration_date"]},
        ),
        migrations.AlterModelOptions(
            name="opportunity",
            options={"ordering": ["-start_date"]},
        ),
        migrations.AlterModelOptions(
            name="studentinterestform",
            options={"ordering": ["-submission_date"]},
        ),
        migrations.AlterModelOptions(
            name="team",
            options={"ordering": ["sport", "name"]},
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="availability",
            field=models.CharField(
                blank=True,
                choices=[
                    ("morning", "Morning"),
                    ("evening", "Evening"),
                    ("both", "Both"),
                    ("weekends", "Weekends Only"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="certificates",
            field=models.FileField(blank=True, null=True, upload_to="certificates/"),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="email_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="experience_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                    ("professional", "Professional"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="fitness_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("low", "Low — Just getting started"),
                    ("moderate", "Moderate — Regular exercise"),
                    ("high", "High — Athlete level"),
                    ("elite", "Elite — Competitive level"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="height_cm",
            field=models.IntegerField(blank=True, help_text="Height in cm", null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="highest_level",
            field=models.CharField(
                blank=True,
                help_text="e.g. District level, State level, National level",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="medical_conditions",
            field=models.TextField(
                blank=True,
                help_text="Any medical conditions the coach should know about",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="onboarding_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="onboarding_step",
            field=models.IntegerField(
                choices=[
                    (0, "Not Started"),
                    (1, "Basic Info Done"),
                    (2, "Sports History Done"),
                    (3, "Sports Interests Done"),
                    (4, "Complete"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="past_achievements",
            field=models.TextField(
                blank=True,
                help_text="Describe your past sports achievements",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="position_played",
            field=models.CharField(
                blank=True,
                help_text="e.g. Batsman, Goalkeeper, Striker",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="sports_interests",
            field=models.ManyToManyField(
                blank=True, related_name="interested_students", to="sports_app.team"
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="weight_kg",
            field=models.IntegerField(blank=True, help_text="Weight in kg", null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="willing_to_travel",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="years_playing",
            field=models.IntegerField(
                blank=True,
                help_text="How many years have you been playing sports?",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="achievements/"),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="player_names",
            field=models.TextField(help_text="Player names separated by commas"),
        ),
        migrations.AlterField(
            model_name="eventregistration",
            name="team_members",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="poster_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="opportunity_posters/"
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="branch",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="roll_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="year",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "1st Year"),
                    (2, "2nd Year"),
                    (3, "3rd Year"),
                    (4, "4th Year"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="team_logo",
            field=models.ImageField(blank=True, null=True, upload_to="team_logos/"),
        ),
    ]
